AWSTemplateFormatVersion: '2010-09-09'
Description: Create s3 buckets for the Argon Dashboard.

Resources:
  StaticWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: argons3bucket
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticWebsiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: "AddPerm"
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: 'arn:aws:s3:::argons3bucket/*'

Outputs:
  WebsiteURL:
    Description: "URL for the static website hosted on S3"
    Value: !GetAtt StaticWebsiteBucket.WebsiteURL

